# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wandering Minds
email: contact@wandering-minds.eu
description: >- 
  Wandering Minds is a software company based in Berlin, Germany. We build and maintain a number of own software products, and offer consulting services around software engineering leadership and development.
baseurl: ""
url: "https://wandering-minds.eu"
company_name: WM Wandering Minds GmbH 

# Social
github_username:  WM-Wandering-Minds
linkedin_companyname: WM-Wandering-Minds
linkedin_username:  monikawiest
appointment_booking_url: https://calendar.app.google/hYxygHeXngLJ8gHn9

# Analytics
google_tag_manager: GTM-K4KNNSN8
google_analytics: G-NCFSSN5X40

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - _pages/consulting.md
  - _pages/projects.md

collections:
  pages:
    output: true
    permalink: /:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
