# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wandering Minds
email: contact@wandering-minds.eu
description: >- # this means to ignore newlines until "baseurl:"
  Wandering Minds is a software company based in Berlin, Germany. We offer consulting services around software engineering leadership and development of web and mobile application.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wandering-minds.eu" # the base hostname & protocol for your site, e.g. http://example.com

company_name: WM Wandering Minds GmbH 
github_username:  WM-Wandering-Minds
linkedin_companyname: WM-Wandering-Minds

google_analytics: G-R3432B747P

show_excerpts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

header_pages: # These are displayed in the header navigation
  - pages/about.md
  # - pages/consulting.md
  # - pages/projects.md
  # - pages/news.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
